### ISSUE TITLE
Test of the Emergency Broadcast System

### ISSUE THREAD

**Issue by megaman-exe** [JP-Robotics/redolent-octo-guacamole#1]
Oh no!  This project has no one working on it yet!  This must be resolved!

Issue reports can be formatted using a github feature called markdown.  This would be a useful skill for the whole team to learn.  Markdown is usable throughout the site, including our webpage.

cc:
@JP-Robotics/software 
@JP-Robotics/other 
@JP-Robotics/hardware

**Comment by jprobotics** [comment]
Excellent! 

Sent from my iPhone

On Sep 1, 2015, at 5:09 PM, Benjamin Wilkinson notifications@github.com wrote:

Oh no! This project has no one working on it yet! This must be resolved!

Issue reports can be formatted using a github feature called markdown. This would be a useful skill for the whole team to learn. Markdown is usable throughout the site, including our webpage.

cc:
@JP-Robotics/software 
@JP-Robotics/other 
@JP-Robotics/hardware

―
